=== DDCM-UGent/workshop_hierarchical_query_languages/data/tweets_schema.json
{
    "$schema":"http://json-schema.org/draft-07/schema#",
    "description": "The json schema for an array of tweets",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "integer"
            },
            "created_at": {
                "type": "string",
                "format": "date-time"
            },
            "content": {
                "type": "string"
            },
            "location": {
                "type": "string"
            },
            "tweeted_by": {
                "$ref": "#/$defs/user"
            },
            "retweets": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "retweeted_by": {
                            "$ref": "#/$defs/user"
                        },
                        "created_at": {
                            "type": "string",
                            "format": "date-time"
                        }
                    },
                    "required": ["retweeted_by", "created_at"]
                }
            },
            "mentions": {
                "$ref": "#/$defs/userlist"
            },
            "likes": {
                "$ref": "#/$defs/userlist"
            }
        },
        "required": ["id", "created_at", "content", "tweeted_by"]
    },
    "$defs": {
        "user": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                }
            },
            "required": ["username"]
        },
        "userlist": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/user"
            }
        }
    }
}

=== DDCM-UGent/workshop_hierarchical_query_languages/data/tweets.json
[
  {
    "id": 164895,
    "created_at": "2019-03-07T14:59:14",
    "content": "https://t.co/5NXPklGB5E",
    "tweeted_by": {
      "username": "AbrilAtenasGmez",
      "description": "vine aqu\u00ed sin saber nada y me ir\u00e9 deseando saberlo todo..."
    }
  },
  {
    "id": 155092,
    "created_at": "2019-03-07T13:37:54",
    "content": "https://t.co/roo9AQwcck",
    "tweeted_by": {
      "username": "Vetrivelchezhi2"
    }
  },
  {
    "id": 118091,
    "created_at": "2019-03-06T15:51:05",
    "content": "Don\u2019t fly off!!! \u201cUndeterred\u201d #Hyderabadi",
    "tweeted_by": {
      "username": "TariqRehmani",
      "description": "Dust!! That\u2019s where we belong to, makes an appropriate epitaph !!",
      "location": "Bengaluru, India"
    }
  },
  {
    "id": 146580,
    "created_at": "2019-03-07T12:25:34",
    "content": "https://t.co/gx3BgA9UyY",
    "tweeted_by": {
      "username": "bossy_jersey",
      "description": "Jersey born Beauty",
      "location": "All Around The World"
    }
  },
  {
    "id": 103172,
    "created_at": "2019-03-06T11:31:31",
    "content": "No hay m\u00e1s l\u00edmites que los que nosotros mismos nos ponemos.\n            #entrepreneurs #emprendedoreszaragoza #emprendedores #startupbusiness #startupgrindzaragoza #startupgrind\n            #zaragozaciudad #startuptips #google\n        ",
    "tweeted_by": {
      "username": "startupgrindzgz",
      "description": "Startup Grind powered by Google es una comunidad de startups global dise\u00f1ada para educar,\n                inspirar y conectar emprendedores. Organizamos eventos mensuales.\n            ",
      "location": "Zaragoza, Espa\u00f1a"
    }
  },
  {
    "id": 101548,
    "created_at": "2019-03-05T09:35:02",
    "content": "https://t.co/gFDzsVBTuE",
    "tweeted_by": {
      "username": "SaraM91466012",
      "description": "Essere se stessi \u00e8 il modo migliore per affrontare la vita a testa alta.\n                Mia figlia, il mio \u2764.\n                \ud83c\udf3aNatura e \ud83d\udd4aanimali.\n                Socia Lipu.\n                Dott.ssa in Scienze Politiche.\n            "
    },
    "retweets": [
      {
        "created_at": "2019-03-06T15:48:46",
        "retweeted_by": {
          "username": "cinziageraci1",
          "location": "palermo"
        }
      },
      {
        "created_at": "2019-03-06T16:05:21",
        "retweeted_by": {
          "username": "michelazbol",
          "description": "amo L'INTER, la mia famiglia e la mia cagnolina Briciola.",
          "location": "Bologna, Emilia Romagna"
        }
      },
      {
        "created_at": "2019-03-06T15:02:35",
        "retweeted_by": {
          "username": "OzzTriscele72",
          "description": "amante dell'arte,dei viaggi,delle cose semplici,del buon cibo e della buona\n                        educazione...\n                    "
        }
      },
      {
        "created_at": "2019-03-06T13:12:32",
        "retweeted_by": {
          "username": "LauraCiriolo",
          "location": "San pancrazio salentino"
        }
      },
      {
        "created_at": "2019-03-06T14:24:20",
        "retweeted_by": {
          "username": "massimo4951",
          "description": "Amo gli animali odio profondamente chi gli maltratta",
          "location": "Modena"
        }
      }
    ],
    "likes": [
      {
        "username": "Belle_Originals",
        "description": "Custom clothing, pressed vinyl, vinyl decals, homecoming mums, pageant wear, & bows!\n                    We've been in business since 2007 and love making custom creations!\n                ",
        "location": "Academy, TX"
      }
    ]
  },
  {
    "id": 136730,
    "created_at": "2019-03-07T10:50:13",
    "content": "https://t.co/rlv7toEUGQ",
    "tweeted_by": {
      "username": "DePassions",
      "description": "Experience passion at a new and exciting level",
      "location": "Dover, DE"
    }
  },
  {
    "id": 142878,
    "created_at": "2019-03-07T11:51:46",
    "content": "\ud83d\udc40\ud83d\udc40\ud83d\udc40\ud83d\udc40\ud83d\udc40\ud83d\udc40\ud83d\udcaa\ud83d\udcaa\ud83d\udcaa\ud83d\udcaa\n            https://t.co/d0aiAvCBu6\n        ",
    "tweeted_by": {
      "username": "ffuli",
      "description": "Operador Radio.",
      "location": "Universidad del Cauca.Popay\u00e1n_"
    }
  },
  {
    "id": 186461,
    "created_at": "2019-03-08T11:40:43",
    "content": "Kwara PDP in aggressive door to door campaign to reclaim @bukolasaraki",
    "tweeted_by": {
      "username": "wagzie01",
      "description": "Husband || Father || Entrepreneur || Livestock Farmer ||",
      "location": "Kwara, Abuja"
    },
    "retweets": [
      {
        "created_at": "2019-03-08T11:40:43",
        "retweeted_by": {
          "username": "GarbaKofa",
          "location": "Zaria, Nigeria"
        }
      },
      {
        "created_at": "2019-03-08T12:15:05",
        "retweeted_by": {
          "username": "yusluvlove",
          "location": "Kwara state"
        }
      },
      {
        "created_at": "2019-03-08T12:48:50",
        "retweeted_by": {
          "username": "gbenga_omolawon",
          "description": "Trust in God",
          "location": "Porhercourt Nigeria"
        }
      },
      {
        "created_at": "2019-03-08T12:54:01",
        "retweeted_by": {
          "username": "bakare_caleb",
          "description": "Ordinary Man with Extraordinary God producing Extraordinary Results.\n\n                        Founder/CEO of Larrystone Investment Holdings and\n                        Advocate of #InvestInKwaraInitiative\n                    ",
          "location": "Global Citizen"
        }
      }
    ],
    "mentions": [
      {
        "username": "bukolasaraki"
      }
    ]
  },
  {
    "id": 144817,
    "created_at": "2019-03-07T12:09:20",
    "content": "Why aren't you using the Nigerian one madam",
    "tweeted_by": {
      "username": "MisterNgini",
      "description": "the game is the game , it won't play itself"
    }
  },
  {
    "id": 103379,
    "created_at": "2019-03-06T11:45:33",
    "content": "Jacob Rees-Mogg is wrong: the Tory party does have an Islamophobia problem - New Statesman\n            https://t.co/InPt6XxBD5\n        ",
    "tweeted_by": {
      "username": "politicswatch15",
      "description": "Covering the Global Politics scene for Hard Copy News @hardcopynews, also @hardcopytech,\n                @hardcopygaynews & @hardcopyusa @hardcopyafrica @hcnsouthamerica\n            ",
      "location": "Worldwide"
    }
  },
  {
    "id": 130907,
    "created_at": "2019-03-07T09:42:39",
    "content": "https://t.co/02miCLd9iB",
    "tweeted_by": {
      "username": "namchimsope"
    }
  },
  {
    "id": 117717,
    "created_at": "2019-03-06T15:48:09",
    "content": "https://t.co/grhmohSim9",
    "tweeted_by": {
      "username": "montesjulia_",
      "description": "I'm just a simple girl trying to make it big in the world!"
    }
  },
  {
    "id": 155247,
    "created_at": "2019-03-07T13:39:12",
    "content": "THE B.O.S.S. MAG\n            \"Yes men... A millennial love affair\"\n\n            \"Antonio Brown has surrounded himself with people that tell him what he wants to hear, not what he needs to\n            know. The biggest mistake current athletes make... https://t.co/onkqjPEgmR\n        ",
    "tweeted_by": {
      "username": "BOSSMAGAZINE2",
      "description": "B.O.S.S. MAGAZINE\n                Blowin Of Some Steam\n            ",
      "location": "Everywhere"
    }
  },
  {
    "id": 180215,
    "created_at": "2019-03-08T10:40:45",
    "content": "https://t.co/0MWt17BoZb",
    "tweeted_by": {
      "username": "Ahmedkashmiri98",
      "description": "Study in Computer Science and im Chairman of Crystal Network ltd.",
      "location": "KARACHI,"
    }
  },
  {
    "id": 145212,
    "created_at": "2019-03-07T12:12:42",
    "content": "https://t.co/OM8CvwsnvD",
    "tweeted_by": {
      "username": "CraigBarbaro"
    }
  },
  {
    "id": 160618,
    "created_at": "2019-03-07T14:23:50",
    "content": "https://t.co/uk6Mc7jZc9",
    "tweeted_by": {
      "username": "alex_6_982"
    }
  },
  {
    "id": 100814,
    "created_at": "2019-02-27T18:05:16",
    "content": "Running Man (2015)\n\n            EP272\n            PART 1 https://t.co/5iofLQxquP\n            PART 2 https://t.co/UFJZ9hkkSN\n            PART 3 https://t.co/hKYepttAaV\n            PART 4 https://t.co/HKke3XTxkz https://t.co/Jc5BjOfeve\n        ",
    "tweeted_by": {
      "username": "BYEWHY17",
      "description": "\u2665 #SEVENTEEN THAISUB \u0e23\u0e27\u0e21\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e15\u0e48\u0e32\u0e07\u0e46\u0e02\u0e2d\u0e07\u0e40\u0e0b\u0e40\u0e27\u0e48\u0e19\u0e17\u0e35\u0e19\n                \u00b7 \u0e2b\u0e32\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e44\u0e21\u0e48\u0e40\u0e08\u0e2d\u0e01\u0e14\u0e14\u0e39\u0e43\u0e19\u0e17\u0e27\u0e34\u0e15\u0e17\u0e35\u0e48\u0e1e\u0e34\u0e19\u0e44\u0e27\u0e49\u0e14\u0e49\u0e32\u0e19\u0e1a\u0e19\u0e19\u0e30\u0e04\u0e30\n                \u25b6\ufe0f Youtube : BYEWHY 17 \ud83d\udccc\n            ",
      "location": "https://www.pinterest.com/byewhy"
    },
    "retweets": [
      {
        "created_at": "2019-03-06T14:42:14",
        "retweeted_by": {
          "username": "LovingMrMoon",
          "description": "'Fall for me and you won't lose a thing' - Wen Junhui\n\n                        #Getting_Closer - SEVENTEEN mv \ud83d\udc47\n\n                        https://youtu.be/eTuR-e6aLRo\n                    ",
          "location": "Seventeen carats - Home \ud83c\udfe1"
        }
      }
    ],
    "likes": [
      {
        "username": "JLARealty",
        "description": "We have a team of over 850 agents across the #HoustonMarket who are ready to assist you in\n                    all your #RealEstate needs. #JLARealty\n                ",
        "location": "Houston/Kingwood, Texas"
      },
      {
        "username": "Soya_SW",
